spring:
  application:
    name: distributor-domain-branding
    version: 1.0.0
    description: Distributor Domain Branding Layer Application
    team:
      name: Firefly Software Solutions Inc
      email: dev@getfirefly.io
  config:
    import: "optional:configserver:https://app-firefly-config-server.dev.soon.es"
  threads:
    virtual:
      enabled: true
